export default [
    {
        id: 32,
        brand: 'Modulyss',
        title: 'Monos',
        slug: 'monos',
        productDescription:
            'Monos brings a touch of elegance to any space by artfully blending colours that balance tranquillity and dynamism. With its subtle duality, the loop pile carpet tile collection Monos transforms interiors, offering both serenity and energy. It features a versatile palette thoughtfully divided into three groups: warm earthy tones for a cosy, inviting feel, neutral and dark shades for a calming yet inspiring atmosphere, and cool jewel tones for a sophisticated, modern aesthetic.',
        applications: ['Entrance', 'Kitchens & bathrooms'],
        materials: ['Carpet'],
        patterns: ['Solid'],
        shades: ['Neutral'],
        features: ['Recycled Content', 'Recyclable'],
        price: '$',
        env: ['GreenTag'],
        shapes: ['Squares'],
        image: '/brand/modulyss/products/monos.webp',
        variants: [
            { name: 'Monos 106', image: '/brand/modulyss/products/monos/variants/monos-106.webp', swatch: '#B78A64' },
            { name: 'Monos 152', image: '/brand/modulyss/products/monos/variants/monos-152.webp', swatch: '#9A8776' },
            { name: 'Monos 204', image: '/brand/modulyss/products/monos/variants/monos-204.webp', swatch: '#8FA0AE' },
            { name: 'Monos 280', image: '/brand/modulyss/products/monos/variants/monos-280.webp', swatch: '#B78A64' },
            { name: 'Monos 283', image: '/brand/modulyss/products/monos/variants/monos-283.webp', swatch: '#C06E4E' },
            { name: 'Monos 319', image: '/brand/modulyss/products/monos/variants/monos-319.webp', swatch: '#5C6D7A' },
            { name: 'Monos 326', image: '/brand/modulyss/products/monos/variants/monos-326.webp', swatch: '#2D3A4B' },
            { name: 'Monos 346', image: '/brand/modulyss/products/monos/variants/monos-346.webp', swatch: '#8B3A3A' },
            { name: 'Monos 406', image: '/brand/modulyss/products/monos/variants/monos-406.webp', swatch: '#CFC8C1' },
            { name: 'Monos 419', image: '/brand/modulyss/products/monos/variants/monos-419.webp', swatch: '#D2D4D3' },
            { name: 'Monos 452', image: '/brand/modulyss/products/monos/variants/monos-452.webp', swatch: '#BFC6CC' },
            { name: 'Monos 517', image: '/brand/modulyss/products/monos/variants/monos-517.webp', swatch: '#8FA0AE' },
            { name: 'Monos 530', image: '/brand/modulyss/products/monos/variants/monos-530.webp', swatch: '#4A6A5B' },
            { name: 'Monos 553', image: '/brand/modulyss/products/monos/variants/monos-553.webp', swatch: '#2F4F3E' },
            { name: 'Monos 567', image: '/brand/modulyss/products/monos/variants/monos-567.webp', swatch: '#3E5A49' },
            { name: 'Monos 577', image: '/brand/modulyss/products/monos/variants/monos-577.webp', swatch: '#7D8488' },
            { name: 'Monos 582', image: '/brand/modulyss/products/monos/variants/monos-582.webp', swatch: '#9AA3A8' },
            { name: 'Monos 592', image: '/brand/modulyss/products/monos/variants/monos-592.webp', swatch: '#5C6D7A' },
            { name: 'Monos 603', image: '/brand/modulyss/products/monos/variants/monos-603.webp', swatch: '#A9ADB0' },
            { name: 'Monos 606', image: '/brand/modulyss/products/monos/variants/monos-606.webp', swatch: '#D6D7D7' },
            { name: 'Monos 626', image: '/brand/modulyss/products/monos/variants/monos-626.webp', swatch: '#2D3A4B' },
            { name: 'Monos 642', image: '/brand/modulyss/products/monos/variants/monos-642.webp', swatch: '#7D8488' },
            { name: 'Monos 823', image: '/brand/modulyss/products/monos/variants/monos-823.webp', swatch: '#BDB3A7' },
            { name: 'Monos 827', image: '/brand/modulyss/products/monos/variants/monos-827.webp', swatch: '#AFA59A' },
            { name: 'Monos 844', image: '/brand/modulyss/products/monos/variants/monos-844.webp', swatch: '#9A8776' },
            { name: 'Monos 847', image: '/brand/modulyss/products/monos/variants/monos-847.webp', swatch: '#8E867F' },
            { name: 'Monos 883', image: '/brand/modulyss/products/monos/variants/monos-883.webp', swatch: '#5A5A5A' },
            { name: 'Monos 908', image: '/brand/modulyss/products/monos/variants/monos-908.webp', swatch: '#D2D4D3' },
            { name: 'Monos 911', image: '/brand/modulyss/products/monos/variants/monos-911.webp', swatch: '#1E2022' },
            { name: 'Monos 957', image: '/brand/modulyss/products/monos/variants/monos-957.webp', swatch: '#D6D7D7' },
            { name: 'Monos 968', image: '/brand/modulyss/products/monos/variants/monos-968.webp', swatch: '#BFC6CC' },
            { name: 'Monos 979', image: '/brand/modulyss/products/monos/variants/monos-979.webp', swatch: '#3E4143' },
            { name: 'Monos 983', image: '/brand/modulyss/products/monos/variants/monos-983.webp', swatch: '#2F3131' },
            { name: 'Monos 989', image: '/brand/modulyss/products/monos/variants/monos-989.webp', swatch: '#5A5A5A' },
            { name: 'Monos 990', image: '/brand/modulyss/products/monos/variants/monos-990.webp', swatch: '#111111' },
            { name: 'Monos 991', image: '/brand/modulyss/products/monos/variants/monos-991.webp', swatch: '#2F3131' }
        ],
        roomshots: [
            '/brand/modulyss/products/monos/roomshots/room-1.webp',
            '/brand/modulyss/products/monos/roomshots/room-2.webp',
            '/brand/modulyss/products/monos/roomshots/room-3.webp',
            '/brand/modulyss/products/monos/roomshots/room-4.webp',
            '/brand/modulyss/products/monos/roomshots/room-5.webp',
            '/brand/modulyss/products/monos/roomshots/room-6.webp'
        ]
    }
];