export default [
    {
        id: 10,
        brand: 'Modulyss',
        title: 'Etch',
        slug: 'etch',
        productDescription:
            'Etch recalls the natural woven structure of linen and adds a highly patterned style to the Artcore collection for you to play with. With a linear design, loop pile texture and a raw, elemental colour palette, Etch makes a seamless transition to Core with the Etch Gradient tile. Create a fluid pattern that moves smoothly from one side of a room to another and defines zones along the way. The Etch collection is 100% made from ECONYL® yarn and holds the Cradle-to-Cradle® certification.',
        applications: ['Entrance', 'Service areas'],
        materials: ['Carpet'],
        patterns: ['Geometric'],
        shades: ['Neutral'],
        features: ['Quick Ship', 'Recyclable'],
        price: '$$',
        env: ['Declare'],
        shapes: ['Squares'],
        image: '/brand/modulyss/products/etch.webp',
        variants: [
            { name: 'Etch 010', image: '/brand/modulyss/products/etch/variants/etch-010.webp', swatch: '#B78A64' },
            { name: 'Etch 012', image: '/brand/modulyss/products/etch/variants/etch-012.webp', swatch: '#8B3A3A' },
            { name: 'Etch 208', image: '/brand/modulyss/products/etch/variants/etch-208.webp', swatch: '#8FA0AE' },
            { name: 'Etch 389', image: '/brand/modulyss/products/etch/variants/etch-389.webp', swatch: '#5C6D7A' },
            { name: 'Etch 398', image: '/brand/modulyss/products/etch/variants/etch-398.webp', swatch: '#2D3A4B' },
            { name: 'Etch 501', image: '/brand/modulyss/products/etch/variants/etch-501.webp', swatch: '#2F4F3E' },
            { name: 'Etch 518', image: '/brand/modulyss/products/etch/variants/etch-518.webp', swatch: '#9A8776' },
            { name: 'Etch 626', image: '/brand/modulyss/products/etch/variants/etch-626.webp', swatch: '#BFC6CC' },
            { name: 'Etch 659', image: '/brand/modulyss/products/etch/variants/etch-659.webp', swatch: '#7D8488' },
            { name: 'Etch 672', image: '/brand/modulyss/products/etch/variants/etch-672.webp', swatch: '#D2D4D3' },
            { name: 'Etch 853', image: '/brand/modulyss/products/etch/variants/etch-853.webp', swatch: '#5A5A5A' },
            { name: 'Etch 901', image: '/brand/modulyss/products/etch/variants/etch-901.webp', swatch: '#2F3131' },
            { name: 'Etch 904', image: '/brand/modulyss/products/etch/variants/etch-904.webp', swatch: '#B78A64' },
            { name: 'Etch 911', image: '/brand/modulyss/products/etch/variants/etch-911.webp', swatch: '#8B3A3A' },
            { name: 'Etch 932', image: '/brand/modulyss/products/etch/variants/etch-932.webp', swatch: '#8FA0AE' },
            { name: 'Etch 983', image: '/brand/modulyss/products/etch/variants/etch-983.webp', swatch: '#5C6D7A' },
            { name: 'Etch Gradient 010', image: '/brand/modulyss/products/etch/variants/etch-010.webp', swatch: '#B78A64' },
            { name: 'Etch Gradient 012', image: '/brand/modulyss/products/etch/variants/etch-012.webp', swatch: '#8B3A3A' },
            { name: 'Etch Gradient 208', image: '/brand/modulyss/products/etch/variants/etch-208.webp', swatch: '#8FA0AE' },
            { name: 'Etch Gradient 389', image: '/brand/modulyss/products/etch/variants/etch-389.webp', swatch: '#5C6D7A' },
            { name: 'Etch Gradient 398', image: '/brand/modulyss/products/etch/variants/etch-398.webp', swatch: '#2D3A4B' },
            { name: 'Etch Gradient 501', image: '/brand/modulyss/products/etch/variants/etch-501.webp', swatch: '#2F4F3E' },
            { name: 'Etch Gradient 518', image: '/brand/modulyss/products/etch/variants/etch-518.webp', swatch: '#9A8776' },
            { name: 'Etch Gradient 626', image: '/brand/modulyss/products/etch/variants/etch-626.webp', swatch: '#BFC6CC' },
            { name: 'Etch Gradient 659', image: '/brand/modulyss/products/etch/variants/etch-659.webp', swatch: '#7D8488' },
            { name: 'Etch Gradient 672', image: '/brand/modulyss/products/etch/variants/etch-672.webp', swatch: '#D2D4D3' },
            { name: 'Etch Gradient 853', image: '/brand/modulyss/products/etch/variants/etch-853.webp', swatch: '#5A5A5A' },
            { name: 'Etch Gradient 901', image: '/brand/modulyss/products/etch/variants/etch-901.webp', swatch: '#2F3131' },
            { name: 'Etch Gradient 904', image: '/brand/modulyss/products/etch/variants/etch-904.webp', swatch: '#B78A64' },
            { name: 'Etch Gradient 911', image: '/brand/modulyss/products/etch/variants/etch-911.webp', swatch: '#8B3A3A' },
            { name: 'Etch Gradient 932', image: '/brand/modulyss/products/etch/variants/etch-932.webp', swatch: '#8FA0AE' },
            { name: 'Etch Gradient 983', image: '/brand/modulyss/products/etch/variants/etch-983.webp', swatch: '#5C6D7A' }
        ],
        roomshots: [
            '/brand/modulyss/products/etch/roomshots/room-1.webp',
            '/brand/modulyss/products/etch/roomshots/room-2.webp',
            '/brand/modulyss/products/etch/roomshots/room-3.webp',
            '/brand/modulyss/products/etch/roomshots/room-4.webp',
            '/brand/modulyss/products/etch/roomshots/room-5.webp',
            '/brand/modulyss/products/etch/roomshots/room-6.webp'
        ]
    }
];