export default [
    {
        id: 30,
        brand: 'Modulyss',
        title: 'Mezzo',
        slug: 'mezzo',
        productDescription:
            'Rooted in the philosophy of biophilia, carpet tile collection Mezzo features a calming organic pattern that reconnects us to nature and offers many mental benefits. This loop pile collection available in a raw, elemental palette enables you to create smooth pattern transitions in your floor layout. Just make a connection to the raw and linear design of Core with the Mezzo Gradient tile and instantly alter the expression of your space in the spirit of a true artist. The Mezzo collection is 100% made from ECONYL® yarn and holds the Cradle-to-Cradle® certification.',
        applications: ['Entrance', 'Service areas'],
        materials: ['Carpet'],
        patterns: ['Textured'],
        shades: ['Neutral'],
        features: ['Quick Ship', 'Green Certificate'],
        price: '$',
        env: ['GreenTag'],
        shapes: ['Squares'],
        image: '/brand/modulyss/products/mezzo.webp',
        variants: [
            { name: 'Mezzo 010', image: '/brand/modulyss/products/mezzo/variants/mezzo-010.webp', swatch: '#D2D4D3' },
            { name: 'Mezzo 012', image: '/brand/modulyss/products/mezzo/variants/mezzo-012.webp', swatch: '#CFC8C1' },
            { name: 'Mezzo 208', image: '/brand/modulyss/products/mezzo/variants/mezzo-208.webp', swatch: '#8FA0AE' },
            { name: 'Mezzo 389', image: '/brand/modulyss/products/mezzo/variants/mezzo-389.webp', swatch: '#5C6D7A' },
            { name: 'Mezzo 398', image: '/brand/modulyss/products/mezzo/variants/mezzo-398.webp', swatch: '#2D3A4B' },
            { name: 'Mezzo 501', image: '/brand/modulyss/products/mezzo/variants/mezzo-501.webp', swatch: '#2F4F3E' },
            { name: 'Mezzo 518', image: '/brand/modulyss/products/mezzo/variants/mezzo-518.webp', swatch: '#4A6A5B' },
            { name: 'Mezzo 626', image: '/brand/modulyss/products/mezzo/variants/mezzo-626.webp', swatch: '#7D8488' },
            { name: 'Mezzo 659', image: '/brand/modulyss/products/mezzo/variants/mezzo-659.webp', swatch: '#A9ADB0' },
            { name: 'Mezzo 672', image: '/brand/modulyss/products/mezzo/variants/mezzo-672.webp', swatch: '#BFC6CC' },
            { name: 'Mezzo 853', image: '/brand/modulyss/products/mezzo/variants/mezzo-853.webp', swatch: '#B78A64' },
            { name: 'Mezzo 901', image: '/brand/modulyss/products/mezzo/variants/mezzo-901.webp', swatch: '#5A5A5A' },
            { name: 'Mezzo 904', image: '/brand/modulyss/products/mezzo/variants/mezzo-904.webp', swatch: '#3E4143' },
            { name: 'Mezzo 911', image: '/brand/modulyss/products/mezzo/variants/mezzo-911.webp', swatch: '#1E2022' },
            { name: 'Mezzo 932', image: '/brand/modulyss/products/mezzo/variants/mezzo-932.webp', swatch: '#8B3A3A' },
            { name: 'Mezzo 983', image: '/brand/modulyss/products/mezzo/variants/mezzo-983.webp', swatch: '#111111' },

            { name: 'Mezzo Gradient 010', image: '/brand/modulyss/products/mezzo/variants/mezzo-gradient-010.webp', swatch: '#D2D4D3' },
            { name: 'Mezzo Gradient 012', image: '/brand/modulyss/products/mezzo/variants/mezzo-gradient-012.webp', swatch: '#CFC8C1' },
            { name: 'Mezzo Gradient 208', image: '/brand/modulyss/products/mezzo/variants/mezzo-gradient-208.webp', swatch: '#8FA0AE' },
            { name: 'Mezzo Gradient 389', image: '/brand/modulyss/products/mezzo/variants/mezzo-gradient-389.webp', swatch: '#5C6D7A' },
            { name: 'Mezzo Gradient 398', image: '/brand/modulyss/products/mezzo/variants/mezzo-gradient-398.webp', swatch: '#2D3A4B' },
            { name: 'Mezzo Gradient 501', image: '/brand/modulyss/products/mezzo/variants/mezzo-gradient-501.webp', swatch: '#2F4F3E' },
            { name: 'Mezzo Gradient 518', image: '/brand/modulyss/products/mezzo/variants/mezzo-gradient-518.webp', swatch: '#4A6A5B' },
            { name: 'Mezzo Gradient 626', image: '/brand/modulyss/products/mezzo/variants/mezzo-gradient-626.webp', swatch: '#7D8488' },
            { name: 'Mezzo Gradient 659', image: '/brand/modulyss/products/mezzo/variants/mezzo-gradient-659.webp', swatch: '#A9ADB0' },
            { name: 'Mezzo Gradient 672', image: '/brand/modulyss/products/mezzo/variants/mezzo-gradient-672.webp', swatch: '#BFC6CC' },
            { name: 'Mezzo Gradient 853', image: '/brand/modulyss/products/mezzo/variants/mezzo-gradient-853.webp', swatch: '#B78A64' },
            { name: 'Mezzo Gradient 901', image: '/brand/modulyss/products/mezzo/variants/mezzo-gradient-901.webp', swatch: '#5A5A5A' },
            { name: 'Mezzo Gradient 904', image: '/brand/modulyss/products/mezzo/variants/mezzo-gradient-904.webp', swatch: '#3E4143' },
            { name: 'Mezzo Gradient 911', image: '/brand/modulyss/products/mezzo/variants/mezzo-gradient-911.webp', swatch: '#1E2022' },
            { name: 'Mezzo Gradient 932', image: '/brand/modulyss/products/mezzo/variants/mezzo-gradient-932.webp', swatch: '#8B3A3A' },
            { name: 'Mezzo Gradient 983', image: '/brand/modulyss/products/mezzo/variants/mezzo-gradient-983.webp', swatch: '#111111' }
        ],
        roomshots: [
            '/brand/modulyss/products/mezzo/roomshots/room-1.webp',
            '/brand/modulyss/products/mezzo/roomshots/room-2.webp',
            '/brand/modulyss/products/mezzo/roomshots/room-3.webp',
            '/brand/modulyss/products/mezzo/roomshots/room-4.webp',
            '/brand/modulyss/products/mezzo/roomshots/room-5.webp',
            '/brand/modulyss/products/mezzo/roomshots/room-6.webp'
        ]
    }
];