export default [
    {
        id: 12,
        brand: 'Modulyss',
        title: 'Fashion&',
        slug: 'fashion&',
        productDescription:
            'Fashion& uses the power of colour for a look that adds personality to any space. The collection acknowledges the diversity in preferences and styles by offering a broad selection of vibrant colour options. The colour palette combined with a loop pile structure, a linear texture and subtle shine, make Fashion& a timeless yet fun carpet tile collection that exudes personality and uniqueness.',
        applications: ['Entrance', 'Kitchens & bathrooms'],
        materials: ['Carpet'],
        patterns: ['Linear'],
        shades: ['Dark'],
        features: ['PVC free', 'Modular'],
        price: '$',
        env: ['Declare'],
        shapes: ['Squares'],
        image: '/brand/modulyss/products/fashion.webp',
        variants: [
            { name: 'Fashion& 105', image: '/brand/modulyss/products/fashion/variants/fashion-105.webp', swatch: '#B78A64' },
            { name: 'Fashion& 136', image: '/brand/modulyss/products/fashion/variants/fashion-136.webp', swatch: '#8B3A3A' },
            { name: 'Fashion& 181', image: '/brand/modulyss/products/fashion/variants/fashion-181.webp', swatch: '#8FA0AE' },
            { name: 'Fashion& 206', image: '/brand/modulyss/products/fashion/variants/fashion-206.webp', swatch: '#5C6D7A' },
            { name: 'Fashion& 240', image: '/brand/modulyss/products/fashion/variants/fashion-240.webp', swatch: '#2D3A4B' },
            { name: 'Fashion& 241', image: '/brand/modulyss/products/fashion/variants/fashion-241.webp', swatch: '#2F4F3E' },
            { name: 'Fashion& 317', image: '/brand/modulyss/products/fashion/variants/fashion-317.webp', swatch: '#9A8776' },
            { name: 'Fashion& 332', image: '/brand/modulyss/products/fashion/variants/fashion-332.webp', swatch: '#BFC6CC' },
            { name: 'Fashion& 375', image: '/brand/modulyss/products/fashion/variants/fashion-375.webp', swatch: '#7D8488' },
            { name: 'Fashion& 381', image: '/brand/modulyss/products/fashion/variants/fashion-381.webp', swatch: '#D2D4D3' },
            { name: 'Fashion& 395', image: '/brand/modulyss/products/fashion/variants/fashion-395.webp', swatch: '#5A5A5A' },
            { name: 'Fashion& 398', image: '/brand/modulyss/products/fashion/variants/fashion-398.webp', swatch: '#2F3131' },
            { name: 'Fashion& 431', image: '/brand/modulyss/products/fashion/variants/fashion-431.webp', swatch: '#B78A64' },
            { name: 'Fashion& 482', image: '/brand/modulyss/products/fashion/variants/fashion-482.webp', swatch: '#8B3A3A' },
            { name: 'Fashion& 512', image: '/brand/modulyss/products/fashion/variants/fashion-512.webp', swatch: '#8FA0AE' },
            { name: 'Fashion& 580', image: '/brand/modulyss/products/fashion/variants/fashion-580.webp', swatch: '#5C6D7A' },
            { name: 'Fashion& 585', image: '/brand/modulyss/products/fashion/variants/fashion-585.webp', swatch: '#2D3A4B' },
            { name: 'Fashion& 595', image: '/brand/modulyss/products/fashion/variants/fashion-595.webp', swatch: '#2F4F3E' },
            { name: 'Fashion& 649', image: '/brand/modulyss/products/fashion/variants/fashion-649.webp', swatch: '#9A8776' },
            { name: 'Fashion& 669', image: '/brand/modulyss/products/fashion/variants/fashion-669.webp', swatch: '#BFC6CC' },
            { name: 'Fashion& 671', image: '/brand/modulyss/products/fashion/variants/fashion-671.webp', swatch: '#7D8488' },
            { name: 'Fashion& 673', image: '/brand/modulyss/products/fashion/variants/fashion-673.webp', swatch: '#D2D4D3' },
            { name: 'Fashion& 678', image: '/brand/modulyss/products/fashion/variants/fashion-678.webp', swatch: '#5A5A5A' },
            { name: 'Fashion& 699', image: '/brand/modulyss/products/fashion/variants/fashion-699.webp', swatch: '#2F3131' },
            { name: 'Fashion& 817', image: '/brand/modulyss/products/fashion/variants/fashion-817.webp', swatch: '#B78A64' },
            { name: 'Fashion& 819', image: '/brand/modulyss/products/fashion/variants/fashion-819.webp', swatch: '#8B3A3A' },
            { name: 'Fashion& 830', image: '/brand/modulyss/products/fashion/variants/fashion-830.webp', swatch: '#8FA0AE' },
            { name: 'Fashion& 832', image: '/brand/modulyss/products/fashion/variants/fashion-832.webp', swatch: '#5C6D7A' },
            { name: 'Fashion& 915', image: '/brand/modulyss/products/fashion/variants/fashion-915.webp', swatch: '#2D3A4B' },
            { name: 'Fashion& 936', image: '/brand/modulyss/products/fashion/variants/fashion-936.webp', swatch: '#2F4F3E' },
            { name: 'Fashion& 942', image: '/brand/modulyss/products/fashion/variants/fashion-942.webp', swatch: '#9A8776' },
            { name: 'Fashion& 950', image: '/brand/modulyss/products/fashion/variants/fashion-950.webp', swatch: '#BFC6CC' },
            { name: 'Fashion& 961', image: '/brand/modulyss/products/fashion/variants/fashion-961.webp', swatch: '#7D8488' },
            { name: 'Fashion& 966', image: '/brand/modulyss/products/fashion/variants/fashion-966.webp', swatch: '#D2D4D3' },
            { name: 'Fashion& 979', image: '/brand/modulyss/products/fashion/variants/fashion-979.webp', swatch: '#5A5A5A' },
            { name: 'Fashion& 990', image: '/brand/modulyss/products/fashion/variants/fashion-990.webp', swatch: '#2F3131' }
        ],
        roomshots: [
            '/brand/modulyss/products/fashion/roomshots/room-1.webp',
            '/brand/modulyss/products/fashion/roomshots/room-2.webp',
            '/brand/modulyss/products/fashion/roomshots/room-3.webp',
            '/brand/modulyss/products/fashion/roomshots/room-4.webp',
            '/brand/modulyss/products/fashion/roomshots/room-5.webp',
            '/brand/modulyss/products/fashion/roomshots/room-6.webp'
        ]
    }
];